import assert from 'node:assert/strict'
import { readFileSync, mkdirSync, writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { spawnSync } from 'node:child_process'
import { chromium } from '@playwright/test'
import { defaults, designTokens, project } from './profile.mjs'
const base=process.env.PILOT_URL||'http://127.0.0.1:3066'
mkdirSync('review',{recursive:true})
const browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'chrome'}:{})})
const context=await browser.newContext({viewport:{width:1280,height:900}})
const page=await context.newPage(), errors=[]
page.on('pageerror',error=>errors.push(error.message))
try{
  await page.goto(base)
  await page.locator('#bodySize').waitFor()
  await page.evaluate(defaults=>localStorage.setItem('north-studio-design',JSON.stringify({draft:{...defaults,version:1,titleSize:72,bodySize:20},applied:{...defaults,version:1}})),defaults)
  await page.reload()
  await page.waitForFunction(()=>document.querySelector('#headingSize')?.value==='72')
  assert.equal(await page.locator('#bodySize').inputValue(),'20')
  await page.locator('#bodySize').focus()
  await page.keyboard.press('ArrowRight')
  assert.equal(await page.locator('#bodySize').inputValue(),'21')
  await page.getByRole('button',{name:'Латунь',exact:true}).click()
  await page.getByRole('button',{name:'Одна колонка',exact:true}).click()
  await page.getByRole('button',{name:'1040',exact:true}).click()
  await page.locator('#apply').click()
  await page.reload()
  await page.waitForFunction(()=>document.querySelector('#bodySize')?.value==='21')
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('north-studio-design')))
  assert.equal(saved.draft.version,2)
  assert.equal(saved.applied.width,1040)
  assert.equal(saved.approved,null)
  const before=await page.evaluate(()=>({font:getComputedStyle(document.querySelector('h1')).fontSize,width:document.querySelector('main').getBoundingClientRect().width}))
  const responsePromise=page.waitForResponse(response=>response.url().endsWith('/export'))
  const downloadPromise=page.waitForEvent('download')
  await page.locator('#approve').click()
  const response=await responsePromise
  assert.equal(response.status(),200,await response.text())
  const result=await response.json()
  const download=await downloadPromise
  await download.saveAs(resolve('review/north-design.tar'))
  await page.reload()
  await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('Проверочно утверждено'))
  const approved=await page.evaluate(()=>JSON.parse(localStorage.getItem('north-studio-design')).approved)
  assert.equal(approved.id,result.id)
  assert.equal(approved.actor,'verification')
  const folder=result.folder, manifest=JSON.parse(readFileSync(resolve(folder,'export-manifest.json'),'utf8'))
  assert.equal(manifest.snapshotId,approved.id)
  assert.ok(manifest.selection.excluded.includes('split'))
  assert.ok(!existsSync(resolve(folder,'editor.mjs')))
  assert.ok(!existsSync(resolve(folder,'core')))
  assert.ok(!readFileSync(resolve(folder,'site.css'),'utf8').includes('data-layout=split'))
  assert.deepEqual(JSON.parse(readFileSync(resolve(folder,'design-snapshot.json'),'utf8')).tokens,designTokens(approved.design))
  const build=spawnSync(process.execPath,['build.mjs'],{cwd:folder,encoding:'utf8'})
  assert.equal(build.status,0,build.stdout+build.stderr)
  await page.locator('#bodySize').focus();await page.keyboard.press('ArrowLeft')
  assert.equal(await page.locator('#status').textContent(),'Изменено после утверждения')
  const id=folder.split(/[\\/]/).at(-1)
  await page.goto(base+'/exports/'+id+'/index.html')
  assert.equal(await page.locator('#studio').count(),0)
  assert.equal(await page.locator('h1').evaluate(element=>getComputedStyle(element).fontSize),before.font)
  assert.equal(await page.locator('main').evaluate(element=>element.getBoundingClientRect().width),before.width)
  for(const width of [375,768,1280]){
    await page.setViewportSize({width,height:900})
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))
    await page.screenshot({path:resolve('review/export-'+width+'.png'),fullPage:true})
  }
  await page.evaluate(()=>document.documentElement.style.fontSize='200%')
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))
  await page.screenshot({path:resolve('review/export-text-200.png'),fullPage:true})
  await page.goto(base+'/?source=offline')
  await page.waitForSelector('[role=alert]')
  assert.match(await page.locator('[role=alert]').textContent(),/недоступны/)
  await page.goto(base)
  await page.locator('#collapse').click()
  await page.getByRole('link',{name:'Наш подход',exact:true}).click()
  assert.ok(page.url().endsWith('#approach'))
  assert.equal(await page.evaluate(()=>document.querySelectorAll(':modal').length),0)
  assert.deepEqual(errors,[])
  writeFileSync('review/result.json',JSON.stringify({project:project.id,approval:approved.id,folder,build:build.stdout,widths:[375,768,1280],textScale:200,errors},null,2))
  console.log(JSON.stringify({folder,approval:approved.id,result:'passed'}))
}finally{await browser.close()}
